### ISSUE TITLE
All of the svFSIplus solver input files in tests are named svFSI.xml rather than svFSIplus.xml

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/svFSIplus#242]
### Description

All of the `svFSIplus/tests/cases` solver input files are named `svFSI.xml`, a leftover from the Fortran svFSI code I guess.

I suppose they could be renamed `svFSIplus.xml` but having all of the files having the same name can cause problems when  copying them around.

But a better solution would be to name them after the problem they are solving, like `pipe_3d.xml`.

### Reproduction

see above

### Expected behavior

see above

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by aabrown100-git** [comment]
@dcodoni @divyaadil23 @elenasmartinez and I discussed this as part of our weekly debugging sessions. We think these files can be left as `svFSI.xml.` Of course, it doesn't hurt to rename them as `svFSIplus.xml` either, but will require a bit of grunt work. We don't think it's necessary to have specific names for these files (e.g. `pipe_3d.xml`), since they exist in dedicated folders for each test case. Also, having every input file named identically makes it easier to recognize the input file.

**Comment by ktbolt** [comment]
@aabrown100-git okey dokey

**Comment by ktbolt** [comment]
I've renamed all the files to `svFSIplus.xml`.

**Comment by dcodoni** [comment]
Great! Thanks @ktbolt !
