### ISSUE TITLE
Couple svFSI with svZeroD

### ISSUE THREAD

**Issue by menon-karthik** [SimVascular/svFSIplus#70]
I implemented a coupling framework between svSolver and svZeroDPlus that allows users to use svZeroDPlus for 0D boundary conditions with 3D svSolver simulations (in place of GenBC). This needs to be implemented for svFSIplus too. 

PS: At the time of creating this issue, the svSolver-svZeroDPlus has not been merged yet, but it will hopefully be merged soon.

**Comment by ktbolt** [comment]
@menon-karthik what is the status of this?

**Comment by kharold23** [comment]
I've gotten two test cases working with sv0DSolver coupled to svFSIplus that match the results from svFSIplus coupled to genBC (which were also validated against svFSI coupled to genBC). I'm working on getting this ready for merging, I just had a few questions/comments:

1. The sv0D interface files are currently in a subfolder of the svFSI code folder-- is this ok? Or would you prefer them to be organized in a different way?

2. We're planning on cloning and compiling sv0DSolver each time we compile svFSIplus in order to run these continuous integration tests. We're still figuring out where this will be located.

**Comment by menon-karthik** [comment]
> I've gotten two test cases working with sv0DSolver coupled to svFSIplus that match the results from svFSIplus coupled to genBC (which were also validated against svFSI coupled to genBC). I'm working on getting this ready for merging, I just had a few questions/comments:
> 
> 1. The sv0D interface files are currently in a subfolder of the svFSI code folder-- is this ok? Or would you prefer them to be organized in a different way?
> 2. We're planning on cloning and compiling sv0DSolver each time we compile svFSIplus in order to run these continuous integration tests. We're still figuring out where this will be located.

Just to add to this - one test is a fluid mechanics case and the other is a structural mechanics case. For the fluid mechanics case (pipe flow with RCR outlet BC), we validated the coupling between svFSIplus and the svZeroDSolver BC using the analytical solution for the RCR outlet. This will be added to the tests. For the structural mechanics case, the validation is against a reference solution from @aabrown100-git.

**Comment by kharold23** [comment]
Also, should we include the genBC test cases? I know Aaron added some for his struct/ustruct cases, but wasn't sure if I should include my fluid test case.

Would we want to combine them into one case like in svFSI? (just a generic 0D coupling test case with options to do it with either genBC or sv0D, except in svFSI it was with genBC or cplBC)

**Comment by aabrown100-git** [comment]
@menon-karthik @kharold23 I think this feature is completed and we can close this issue. Can you confirm?

**Comment by menon-karthik** [comment]
Yup!

**Comment by aabrown100-git** [comment]
Closing!
